# Generated by Django 5.1.7 on 2025-04-03 02:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_no', models.CharField(max_length=200)),
                ('serial_no', models.CharField(max_length=50, unique=True)),
                ('svc_status', models.CharField(choices=[('serviceable', 'S'), ('unserviceable', 'U/S')], max_length=50)),
                ('remark', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('service_no', models.CharField(max_length=50, unique=True)),
                ('rank', models.CharField(choices=[('Aircraftman', 'ACM'), ('L/Corporal', 'LCPL'), ('Corporal', 'CPL'), ('Sergeant', 'SGT'), ('F/Sergeant', 'FS'), ('Warrant Officer', 'WO'), ('Master Warrant Officer', 'MWO'), ('Air Warrant Officer', 'AWO'), ('Pilot Officer', 'PLT OFFR'), ('Fliying Officer', 'FG OFFR'), ('Flight Luietenant', 'FLT LT'), ('Squadron Leader', 'SQN LDR'), ('Wing Commander', 'WG CDR'), ('Group Captain', 'GP CAPT'), ('Air Commordore', 'AIR CDR'), ('Air Vice Marshal', 'AVM')], max_length=30)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Periodic', 'Periodic'), ('Preventive', 'Preventive'), ('Category A', 'Category A'), ('Category B', 'Category B'), ('Category C', 'Category C'), ('Category D', 'Category D')], max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('priority_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=255)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.equipment')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_record', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
    ]
