# Generated by Django 5.1.7 on 2025-04-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_technician_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
