# Generated by Django 5.1.7 on 2025-04-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='svc_status',
            field=models.CharField(choices=[('S', 'Serviceable'), ('U/S', 'Unserviceable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task.equipment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(choices=[('TM', 'Periodic maintenance'), ('PM', 'Preventive maintenance'), ('CAM', 'Category A maintenance'), ('CBM', 'Category B maintenance'), ('CCM', 'Category C maintenance'), ('CDM', 'Category D maintenance')], max_length=200),
        ),
    ]
